
-- GPT error enums.
GNIL_GPT_ERRORS_CANCELLED = 1
GNIL_GPT_ERRORS_RESPONSE = 2
GNIL_GPT_ERRORS_INVALID = 3
GNIL_GPT_ERRORS_TIMEOUT = 4
GNIL_GPT_ERRORS_COUNT = 4

-- GPT NPC state enums.
GNIL_GPT_NPC_STATE_IDLE = 1
GNIL_GPT_NPC_STATE_LISTENING = 2
GNIL_GPT_NPC_STATE_THINKING = 3
GNIL_GPT_NPC_STATE_SPEAKING = 4
GNIL_GPT_NPC_STATE_BUSY = 5
GNIL_GPT_NPC_STATE_COUNT = 5

if SERVER then

    -- Speech providers.
    GNIL_GPT_SPEECH_PROVIDER_ELEVENLABS = 1
    GNIL_GPT_SPEECH_PROVIDER_GOOGLECLOUD = 2
    GNIL_GPT_SPEECH_PROVIDER_COUNT = 2

    -- Interaction task terminator.
    GNIL_GPT_INTERACTION_TASK_GPT = 1
    GNIL_GPT_INTERACTION_TASK_TTS = 2
    GNIL_GPT_INTERACTION_TASK_COUNT = 2

end