local MODULE = MODULE
GNIL.GPT.TOS = GNIL.GPT.TOS or {
	["_r"] = {},
	["_c"] = nil
}

-- Use a "semi-secret" hash generated by the server to verify that
-- the player has accepted the TOS for the server. This hash approach
-- allows all players that have previously accepted the TOS to be reset
-- just by changing the hash salt. (For potential TOS edits).

if CLIENT then
	local LocalPlayer = LocalPlayer

	local ScrW, ScrH = ScrW, ScrH
	local function ss(n) return n * ( ScrW() / 1920 ) end
	-- Receive hash request, sending back if there is one.
	MODULE:GetExtension("net"):Receive("gpt_tos", function()
		local out = LocalPlayer():GetPData("gpt_tos_hash")
		local reply = GNIL.Net.CreateReply():WriteBool(out != nil)
		if out != nil then
			reply:WriteString(out)
		end
		GNIL.GPT.TOS["_c"] = Either(out == nil, false, out)
		return reply
	end)

	function GNIL.GPT.TOS.OpenTOS()
		if IsValid(LocalPlayer()._gpt_tos_form) then return end
		local t = vgui.Create("gpt_tos_form")
		LocalPlayer()._gpt_tos_form = t
		t:SetSize(ss(600),ss(600))
		t:Center()
		t:SetY(ScrH())
		t:CreateAnimation(.75, {
			index = 1,
			target = {positionY = ScrH() * .5 - ss(600) * .5},
			easing = "inOutQuad",
			Think = function(slf,pnl)
				pnl:SetY(pnl.positionY)
			end,
		})
		function t:TOSAccept()
			GNIL.GPT.TOS.Accept()
		end
		function t:TOSDeny()
			GNIL.GPT.TOS.Deny()
		end

		return t
	end

	-- Send TOS accept message and recieve the valid hash to store.
	function GNIL.GPT.TOS.Accept()
		GNIL.Net.Create("gpt_tos")
			:WriteBit(1)
			:OnReply(function(success)
				if success and net.ReadBool() then
					local str = net.ReadString()
					GNIL.GPT.TOS["_c"] = str
					LocalPlayer():SetPData("gpt_tos_hash", str)
				end
			end)
		:SendToServer()
	end

	-- renamed this to Deny, close enough to Reset
	function GNIL.GPT.TOS.Deny()
		LocalPlayer()._gpt_tos_seen = true
		if LocalPlayer():GetPData("gpt_tos_hash") and not LocalPlayer():RemovePData("gpt_tos_hash") then
			MODULE:log("Failed to remove TOS hash pdata due to local SQL failure.", "error")
		end
		GNIL.GPT.TOS["_c"] = false
		GNIL.Net.Create("gpt_tos")
			:WriteBit(0)
		:SendToServer()
	end

	function GNIL.GPT.TOS.HasSeenTOS()
		return LocalPlayer()._gpt_tos_seen
	end

	-- Cached check to see if TOS has been accepted or not.
	-- Server should validate anyway, just for UI use.
	function GNIL.GPT.TOS.HasAccepted()
		local out = false
		if GNIL.GPT.TOS["_c"] == nil then
			out = LocalPlayer():GetPData("gpt_tos_hash")
			GNIL.GPT.TOS["_c"] = Either(out == nil, false, out)
		else
			out = GNIL.GPT.TOS["_c"]
		end
		return out != false and out != nil
	end

else

	-- TODO: Maybe add a serverside secret hash?
	local function getHash(steamid)
		return util.SHA256("TODO: server hash" .. steamid)
	end

	-- If the player sends a message back, they're accepting
	-- the TOS. Send the correct hash back and cache state.
	GNIL.Net.AddNetworkStrings("gpt_tos", "gpt_tos_show")

	MODULE:GetExtension("net"):Receive("gpt_tos", function(_, ply)
		local steamid = ply:SteamID64()
		ply._gpt_tos_seen = true
		-- Remove request. Player TOS state is being removed.
		if net.ReadBit() == 0 then
			GNIL.GPT.TOS["_r"][steamid] = false
			return
		end

		-- Don't send a hash back if the player already accepted TOS.
		local exists = GNIL.GPT.TOS["_r"][steamid] == true
		local reply = GNIL.Net.CreateReply():WriteBool(not exists)
		if exists then return reply end
		GNIL.GPT.TOS["_r"][steamid] = true
		return reply:WriteString(getHash(steamid))
	end)

	MODULE:AddHook("PlayerNetLoad", "gpt_tos", function(ply)

		-- Send the TOS hash request when the player first joins.
		-- This means that we don't have to send a message each time
		-- we want to check if the player has accepted.
		local steamid = ply:SteamID64()
		GNIL.Net.Create("gpt_tos")
			:OnReply(function(success)
				if not success then return end

				local out = false
				if net.ReadBool() then

					-- Check that the returned hash is valid.
					out = getHash(steamid) == net.ReadString()
					if out then MODULE:log("Player " .. ply:ToString() .. " joined with already accepted TOS.", "debug") end
				end
				GNIL.GPT.TOS["_r"][steamid] = out
			end)
		:Send(ply)
	end)

	function GNIL.GPT.TOS.ShowTOS(ply)
		GNIL.Net.Create("gpt_tos_show"):Send(ply)
	end

	function GNIL.GPT.TOS.HasSeenTOS(ply)
		return ply._gpt_tos_seen
	end

	function GNIL.GPT.TOS.HasAccepted(ply)

		local steamid = ply
		if not isstring(ply) and IsPlayer(ply) then steamid = ply:SteamID64() end
		assert(isstring(steamid), "Provided steamid must be a string.")

		-- Get the TOS state from cache.
		return GNIL.GPT.TOS["_r"][steamid] == true
	end
end